#!/bin/bash
unset IFS
set -eufo pipefail

#
# Sync changes between local and remote for current git branch
#

usage() {
    printf "Usage: %s [OPTIONS]\n\n" "$0"
    printf -- "-m <message>\tApply custom commit message\n"
    printf -- "-n\t\tEnable nonce\n"
    printf -- "-q\t\tQuiet logs\n"
    printf -- "-h\t\tShow usage menu\n"
}

MESSAGE='up'
NONCE=0
QUIET=0

while [[ "$#" -gt 0 ]]; do
    ARG="$1"

    case "$ARG" in
        '-h')
            usage
            exit
            ;;
        '-m')
            shift

            if [[ "$#" -lt 1 ]]; then
                usage
                exit 1
            fi

            MESSAGE="$1"
            shift
            ;;
        '-n')
            NONCE=1
            shift
            ;;
        '-q')
            QUIET=1
            shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [[ "$QUIET" -ne 1 ]]; then
    set -x
fi

git fetch --all

if [[ "$NONCE" -eq 1 ]]; then
    date >.kick
fi

git add .

if [[ -n "$(git status --porcelain)" ]]; then
    git commit -m "$MESSAGE"
fi

git pull
git push
git fetch --tags

git push --tags
